Set background color white for smoke plots
NOAA-GSL/pygraf pull request #172
Opened 2022-09-30 20:30 UTC by kayeekayee

Changed the lowest value colors be actual white instead of pale blue for both integrated smoke and near surface smoke.

The following plots show the changes of the actual white (left) and original pale blue color (right):

<img width="1424" alt="smoke_int_before_after" src="https://user-images.githubusercontent.com/22350118/193351011-a9179eab-a707-4292-b661-29d63114600c.png">

<img width="1424" alt="smoke_sfc_before_after" src="https://user-images.githubusercontent.com/22350118/193351015-237c7bab-7d69-43c9-ab3b-7f8e2a33e229.png">

Please review.

2022-09-30 21:41 UTC, Brian-Jamison approved these changes
Looks good!

2022-10-01 19:38 UTC, christinaholtNOAA requested changes
@kayeekayee Thanks for this contribution. I know Ravan will be happy to see the change finally made. 

Please make sure the linter is happy with a 10/10 score. If you need help with that, let us know. :)

2022-10-01 19:38 UTC, christinaholtNOAA commented on adb_graphics/specs.py
> +        blues = cm.get_cmap('Blues', 15)([2,5,8,11])
To leave the blues just as they were before as Ravan requested, you should be able to leave it with the more straightforward:

```
blues = cm.get_cmap('Blues', 6)(range(1, 5))
```

2022-10-05 21:10 UTC, christinaholtNOAA approved these changes
Thanks for those changes, @kayeekayee! Looks like it's just down to one tiny change to pass the linter, but I'm good with merging it after that.

2022-10-05 21:10 UTC, christinaholtNOAA commented on adb_graphics/specs.py
> +        return np.concatenate((white,blues, green_yellow_red, purple))
I think the linter is grumbling wanting a space between `white,` and `blues`.

2022-10-05 21:25 UTC, cshartsough approved these changes
agree, it's nice work.  dang that linter, always keeping us honest.  :-)  looks good.

2022-10-06 17:32 UTC, christinaholtNOAA commented
@kayeekayee Do you have the necessary permissions to merge the PR? If so, go for it! :)

If not, let me know and I will fix that.

2022-10-06 17:57 UTC, merged